# -*- coding: utf-8 -*-
"""classe.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pHNUEQyyBH5RoC5UjIXjE-fMIULosBep
"""

class Carro:
  def __init__(self, nome, ligado = False, velocidade = 0):
    self.nome = nome
    self.ligado = ligado
    self.velocidade = velocidade
  
  def ligar_o_carro(self):
    if self.ligado is True:
      print(f'O {self.nome} já está ligado')
    else:
      print(f'Ligando o {self.nome}')
      self.ligado = True
  
  def acelerar(self):
    if self.ligado is True:
      self.velocidade +=(15)
      print(f'O {self.nome} está acelerando \n e a velocidade é atual é {self.velocidade}')
    else:
      print(f'Você não pode acelerar o {self.nome} desligado.')
  
  def freiar(self):
    if self.ligado is True:
      self.velocidade -=(5)
    elif self.ligado is False:
      print('Você não pode freiar um carro desligado')
    if self.velocidade <=(0):
      print(f'O {self.nome} está parado')
    elif self.velocidade >0:
      print(f'diminuindo velocidade do {self.nome}')
    elif self.velocidade <= 0:
      print('O carro está parado')

  
  
  
  def desligar(self):
    if self.ligado is False:
      print(f'o {self.nome} já está desligado')
    else:
      self.ligado = False
      self.velocidade = 0
      print(f'Desligando o {self.nome}')





carro1 = Carro('Camaro')
carro1.nome

carro2 = Carro('Argo')

carro2.ligar_o_carro()

